### ISSUE TITLE
Option to server insight from /

### ISSUE THREAD

**Issue by WebWeave** [str4d/insight-ui-zcash#5]
Hello, how does one server insight from / like https://explorer.testnet.z.cash/ ?
Thanks in advance!

**Comment by karelbilek** [comment]
Hello

It's hard to find and it's not documented much, but it's actually super simple

Add this to your bitcore-node.json

````json
    "insight-ui-zcash": {
      "routePrefix": "",
      "apiPrefix": "api"
    },
    "insight-api-zcash": {
      "routePrefix": "api",
      "enableCache": true
    }
````
